name       : sed
version    : '4.6'
release    : 8
source     :
    - https://ftp.gnu.org/gnu/sed/sed-4.6.tar.xz : beff6acf1c7838cc722714d143a64e706e2fd3bd1e00d3cd75152f596b09bb9e
homepage   : https://www.gnu.org/software/sed/
license    : GPL-3.0-or-later
component  : system.base
summary    : sed (Stream Editor)
description: |
    sed is a stream editor that is meant for manipulating, parsing, and transfoming text.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    install -dm00644 $installdir/bin
    ln -s /usr/bin/sed $installdir/bin/sed
