name       : sed
version    : '4.8'
release    : 11
source     :
    - https://ftp.gnu.org/gnu/sed/sed-4.8.tar.xz : f79b0cfea71b37a8eeec8490db6c5f7ae7719c35587f21edb0617f370eeff633
homepage   : https://www.gnu.org/software/sed/
license    : GPL-3.0-or-later
component  : system.base
summary    : sed (Stream Editor)
description: |
    sed is a stream editor that is meant for manipulating, parsing, and transfoming text.
setup      : |
    %patch -p1 < $pkgfiles/0001-testsuite-disable-panic-tests.sh.patch

    %reconfigure
build      : |
    %make
install    : |
    %make_install
    install -dm00755 $installdir/bin
    ln -s /usr/bin/sed $installdir/bin/sed
check      : |
    %make check
