name       : sed
version    : 4.7
release    : 9
source     :
    - https://ftp.gnu.org/gnu/sed/sed-4.7.tar.xz : 2885768cd0a29ff8d58a6280a270ff161f6a3deb5690b2be6c49f46d4c67bd6a
homepage   : https://www.gnu.org/software/sed/
license    : GPL-3.0-or-later
component  : system.base
summary    : sed (Stream Editor)
description: |
    sed is a stream editor that is meant for manipulating, parsing, and transfoming text.
setup      : |
    %patch -p1 < $pkgfiles/0001-testsuite-disable-panic-tests.sh.patch

    %reconfigure
build      : |
    %make
install    : |
    %make_install
    install -dm00755 $installdir/bin
    ln -s /usr/bin/sed $installdir/bin/sed
check      : |
    %make check
