name       : sed
version    : '4.4'
release    : 6
source     :
    - ftp://ftp.gnu.org/gnu/sed/sed-4.4.tar.xz : cbd6ebc5aaf080ed60d0162d7f6aeae58211a1ee9ba9bb25623daa6cd942683b
homepage   : http://www.gnu.org/software/sed
license    : GPL-3.0
component  : system.base
summary    : sed (Stream Editor)
description: |
    sed is a stream editor that is meant for manipulating, parsing, and transfoming text.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    install -dm00644 $installdir/bin
    ln -s /usr/bin/sed $installdir/bin/sed
